workflows:
  cide-demo-workflow:
    name: Demo pipeline
    environment:
      groups:
      - admin
    scripts:
    -   name: CICD started
        script: echo "Welcome to your CICD set up"
    -   name: Build demo
        script: xcodebuild build -project "cicd-demo.xcodeproj" -scheme "cicd-demo" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    -   name: Build ipa for distribution
        script: |
          xcode-project build-ipa -project "cicd-demo.xcodeproj" -scheme "cicd-demo"
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM        
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        ios:
          app_id: 1:171693901637:ios:3c451d42bb6a43bd09202c
          groups:
            - iosTesters
