workflows:
  cide-demo-workflow:                # workflow ID
    name: Demo pipeline    # workflow name displayed in Codemagic UI
    scripts:
    -   name: CICD started
        script: echo "Welcome to your CICD set up"
    -   name: Build demo
        script: xcodebuild build -project "cicd-demo.xcodeproj" -scheme "cicd-demo" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    publishing:
        email:
            recipients:
            -   "karlos.dev416@gmail.com"
